export const agentManagementActionTypes = {

    //Agent Listing
    FETCH_AGENT_LISTING: "FETCH_AGENT_LISTING",
    FETCH_AGENT_LISTING_SUCCESS: "FETCH_AGENT_LISTING_SUCCESS",
    FETCH_AGENT_LISTING_FAILURE: "FETCH_AGENT_LISTING_FAILURE",

    CLEAR_AGENT_LISTING: "CLEAR_AGENT_LISTING",

    UPDATE_AGENT_LISTING_DATA: 'UPDATE_AGENT_LISTING_DATA',

    UPDATE_AGENT_STATUS: 'UPDATE_AGENT_STATUS',
    UPDATE_AGENT_STATUS_SUCCESS: 'UPDATE_AGENT_STATUS_SUCCESS',
    UPDATE_AGENT_STATUS_FAILURE: 'UPDATE_AGENT_STATUS_FAILURE',

    FETCH_AGENT_RELATIONSHIP_MANAGERS: "FETCH_AGENT_RELATIONSHIP_MANAGERS",
    FETCH_AGENT_RELATIONSHIP_MANAGERS_SUCCESS: "FETCH_AGENT_RELATIONSHIP_MANAGERS_SUCCESS",
    FETCH_AGENT_RELATIONSHIP_MANAGERS_FAILURE: "FETCH_AGENT_RELATIONSHIP_MANAGERS_FAILURE",

    CREATE_OR_UPDATE_AGENT: "CREATE_OR_UPDATE_AGENT",
    CREATE_OR_UPDATE_AGENT_SUCCESS: "CREATE_OR_UPDATE_AGENT_SUCCESS",
    CREATE_OR_UPDATE_AGENT_FAILURE: "CREATE_OR_UPDATE_AGENT_FAILURE",

    RESET_SAVE_AGENT: 'RESET_SAVE_AGENT',

    FETCH_AGENT_DETAILS: 'FETCH_AGENT_DETAILS',
    FETCH_AGENT_DETAILS_SUCCESS: 'FETCH_AGENT_DETAILS_SUCCESS',
    FETCH_AGENT_DETAILS_FAILURE: 'FETCH_AGENT_DETAILS_FAILURE',

    DELETE_DOCUMENTS: 'DELETE_DOCUMENTS',

    DOWNLOAD_DOCUMENT: 'DOWNLOAD_DOCUMENT',

    UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
    UPLOAD_DOCUMENT_SUCCESS: 'UPLOAD_DOCUMENT_SUCCESS',
    UPLOAD_DOCUMENT_FAILURE: 'UPLOAD_DOCUMENT_FAILURE',
    RESET_UPLOAD_DOCUMENT_STATUS: 'RESET_UPLOAD_DOCUMENT_STATUS',



    ADD_TAG_DOCUMENTS: 'ADD_TAG_DOCUMENTS',
    ADD_TAG_DOCUMENTS_SUCCESS: 'ADD_DOCUMENTS_SUCCESS',
    ADD_TAG_DOCUMENTS_FAILURE: 'ADD_DOCUMENTS_FAILURE',
    RESET_ADD_TAG_STATUS: 'RESET_ADD_TAG_STATUS',

    FETCH_AGENT_BINDERS: 'FETCH_AGENT_BINDERS',
    FETCH_AGENT_BINDERS_SUCCESS: 'FETCH_AGENT_BINDERS_SUCCESS',
    FETCH_AGENT_BINDERS_FAILURE: 'FETCH_AGENT_BINDERS_FAILURE',

    FETCH_AGENT_POLICY: 'FETCH_AGENT_POLICY',
    FETCH_AGENT_POLICY_SUCCESS: 'FETCH_AGENT_POLICY_SUCCESS',
    FETCH_AGENT_POLICY_FAILURE: 'FETCH_AGENT_POLICY_FAILURE',
}
